name: farm_fresh
description: The Farm Fresh app connects consumers with locally sourced, fresh produce directly from farms in their area. With a user-friendly interface, the app allows customers to browse a wide selection of fruits, vegetables, dairy, and more, all harvested or produced locally.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  webview_flutter: ^4.2.4
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0
  dio: ^5.1.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.1
  device_info_plus: ^8.0.0
  image_picker: ^0.8.6+1
  file_picker: ^5.2.0+1
  permission_handler: ^10.0.2
  pinput: ^3.0.1
  flutter_native_splash: ^2.3.7
  fluttertoast: ^8.2.4
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  image_cropper: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"


flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
        - asset: assets/fonts/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Medium.ttf
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora-Thin.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  branding: "assets/images/branding.png"

flutter_native_splash:
  color: "#D9EEE9"
  image: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    color: "#D9EEE9"

  android_gravity: center
  ios_content_mode: center
  fullscreen: true