// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHE9mxwCQrsfDshyb9SBABWsHfAMu3hCg',
    appId: '1:82901182179:android:ffeb361a10be75801007d6',
    messagingSenderId: '82901182179',
    projectId: 'xatchup-698d5',
    storageBucket: 'xatchup-698d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiZLdBtpcU2oDgiYExhdQTV-43eNeRc6g',
    appId: '1:82901182179:ios:10b09ffaa58c04f11007d6',
    messagingSenderId: '82901182179',
    projectId: 'xatchup-698d5',
    storageBucket: 'xatchup-698d5.appspot.com',
    androidClientId: '82901182179-id8pr746a3td6rn276jofva32c9utcqb.apps.googleusercontent.com',
    iosClientId: '82901182179-tio6nkr7grmuo2eo0kb4ebgq0t4va357.apps.googleusercontent.com',
    iosBundleId: 'com.ktr.farmFresh',
  );
}
